[package]
name = "plonk-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.12.0"
group = "0.12.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
rand_chacha = "0.3.1"
halo2_curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.2.1", package = "halo2curves" }

# halo2
blake2b_simd = { version = "1.0.0", optional = true }
halo2_proofs = { version = "0.2.0", optional = true }
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "ecc", optional = true }
halo2_wrong_transcript = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "transcript", optional = true }
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon", branch = "padding", optional = true }
rayon = { version = "1.5.1", optional = true }

# evm
ethereum_types = { package = "ethereum-types", version = "0.13.1", default-features = false, features = ["std"], optional = true }
foundry_evm = { git = "https://github.com/foundry-rs/foundry", package = "foundry-evm", rev = "93ee742d", optional = true }
crossterm = { version = "0.22.1", optional = true }
tui = { version = "0.16.0", default-features = false, features = ["crossterm"], optional = true }
sha3 = { version = "0.10.1", optional = true }

[dev-dependencies]
paste = "1.0.7"

[features]
default = ["halo2", "evm"]
test = ["halo2", "evm"]

halo2 = ["dep:blake2b_simd", "dep:halo2_proofs", "dep:halo2_wrong_ecc", "dep:halo2_wrong_transcript", "dep:poseidon", "dep:rayon"]
evm = ["dep:foundry_evm", "dep:crossterm", "dep:tui", "dep:ethereum_types", "dep:sha3"]
sanity-check = []

[patch.crates-io]
halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "experiment", package = "halo2_proofs" }

[patch."https://github.com/privacy-scaling-explorations/halo2"]
halo2_proofs = { git = "https://github.com/han0110/halo2", branch = "experiment", package = "halo2_proofs" }

[patch."https://github.com/privacy-scaling-explorations/halo2curves"]
halo2_curves = { git = "https://github.com//privacy-scaling-explorations/halo2curves", tag = "0.2.1", package = "halo2curves" }

[patch."https://github.com/privacy-scaling-explorations/halo2wrong"]
halo2_wrong = { git = "https://github.com/han0110/halo2wrong", branch = "feature/generic-instructions", package = "halo2wrong" }
halo2_wrong_ecc = { git = "https://github.com/han0110/halo2wrong", branch = "feature/generic-instructions", package = "ecc" }
halo2_wrong_maingate = { git = "https://github.com/han0110/halo2wrong", branch = "feature/generic-instructions", package = "maingate" }
halo2_wrong_transcript = { git = "https://github.com/han0110/halo2wrong", branch = "feature/generic-instructions", package = "transcript" }
